### ISSUE TITLE
タイムラインが正常にストリームされない場合がある

### ISSUE THREAD

**Issue by marihachi** [Frost-Dev/Frost-API#117]
投稿自体は今のところ成功しているので、WebSocketを通じて投稿された後の各タイムラインストリームへ配信する処理が不安定（？）なのだと思う。

でも、StreamingServerは特に変更はしていないし...
謎すぎる

**Comment by marihachi** [comment]
謎タグが付いた

**Comment by Asteriskx** [comment]
ローカル環境でいったん同問題が起こるか見てみますわ

**Comment by marihachi** [comment]
ローカル環境で起こらなそう
厄介だなあ...

**Comment by marihachi** [comment]
少しわかったことなど
- フロントエンド-API間の不具合
- WebSocketのコネクション由来の不具合の可能性あり
- Redis由来の不具合の可能性あり
- クライアントからRESTのリクエストメッセージを送信、サーバからのレスポンスメッセージの受信に関しては正常に行われる。(謎)
  - →もしかして古いWSコネクションをサーバが保持していたりする？
- ローカル環境だとこの不具合が発生しない(謎)

**Comment by marihachi** [comment]
タイムラインの購読が解除されているようにも見える

正常
![image](https://user-images.githubusercontent.com/10358431/46252427-6059a080-c4a3-11e8-8c89-70afa90e71d1.png)

不正
![image](https://user-images.githubusercontent.com/10358431/46252431-66e81800-c4a3-11e8-823b-e40478fb706f.png)

**Comment by marihachi** [comment]
サーバのログより
![image](https://user-images.githubusercontent.com/10358431/46252533-d4487880-c4a4-11e8-82d1-372d5566cdde.png)

`streaming/stream`は、WSコネクション上から`timeline-connect`されている時に配信されるTLの更新データ。
1行目では、ポストの投稿が行われている。
2～5行目では、`streaming/stream`が4人に配信されようとして、`not connected`によって3件が失敗している。
`not connected`はWSコネクションのconnectedプロパティがfalseになっていた場合に表示され、配信を諦めたことを表す。

`not connected`は、WSコネクションが非closeで且つ、connectedがfalseになっていると表示される。(なぜその状態が続くのか..)
そもそも、WSコネクションが正常にcloseされた場合は、配信のイベントハンドラが解除されるので、配信の処理は行われない。→ `not connected`は表示されない。

**Comment by marihachi** [comment]
多分直ったのでclose
