### ISSUE TITLE
各モジュールのフローを図示化する

### ISSUE THREAD

**Issue by Asteriskx** [Frost-Dev/Frost-API#13]
コメントでは補えない部分が出てくる為。

**Comment by marihachi** [comment]
@Asteriskx 
補えない部分とは具体的にどういうところですか
またどういう図が適していますかね
クラス図...？パッケージ図？

**Comment by marihachi** [comment]
またどういう図が適していますかね

**Comment by marihachi** [comment]
クラスの各メソッドの処理は1つの細かな操作だけ(例えば keyGenerateならキーの構築とDBへの書き込みのみなど)もしくはそれが大きな処理である場合はメソッドを小さく切り出して呼び出しているつもりなので、フローチャートまではいらないと思います

**Comment by Asteriskx** [comment]
@marihachi
クラス図に近いイメージは持ってたかな
Frost としてはフローは書かないという結論で
行きますか？
(私個人レベルでは書くつもりではある

**Comment by marihachi** [comment]
@Asteriskx 
書かなくても大丈夫だと思ってる

**Comment by Asteriskx** [comment]
@marihachi
承知。
