### ISSUE TITLE
ポストの種類として何を用意するか

### ISSUE THREAD

**Issue by marihachi** [Frost-Dev/Frost-API#22]
どんな種類のポストを作ろうか
# 検討中の種類
- Status
  短文の投稿記事
- Article
  ブログ記事のように長文を入力可能(記事タイトルを設定可能)
- Reference
  投稿の共有に利用される投稿

他にどんな種類があればいいかな

**Comment by Asteriskx** [comment]
・Sites
URL専用みたいなのあると便利かも

**Comment by marihachi** [comment]
@Asteriskx 
Sitesだとどういう追加情報を付加できるといいだろう
どういう価値があるかな

**Comment by Asteriskx** [comment]
Article の グループに Sites が属してるイメージ
だから別にポストの種類としては増やさなくていいという結論に至ったんだけど

**Comment by marihachi** [comment]
webでの挙動だと、マウスポインタをurlに乗せるとその内容の概略的なものが表示されるといいかもしれない

**Comment by ghost** [comment]
Twitter Cardみたいなやつかな

**Comment by 072** [comment]
titleとdescriptionが見れると便利

**Comment by Asteriskx** [comment]
MouseOver 機能はいいね
User が興味を持っているジャンル表示等も考えたりはした

**Comment by marihachi** [comment]
twitterのタグみたいなのをフォローして、それが付いた投稿をTLに流すみたいなのいいなって思った

**Comment by marihachi** [comment]
その機能案についてissue立てといた
https://github.com/Frost-Dev/Frost/issues/7

**Comment by marihachi** [comment]
他にはポストの種類としてあったら良さそうなの無いかね

**Comment by potato4d** [comment]
いわゆるReTweetはstatusのパラメータとして付加する感じ？

**Comment by marihachi** [comment]
ぜんぜん考えてなかった
共有っていう観点から言えば、元のポストを参照できればそれでいい気がする

**Comment by otofune** [comment]
参照型の投稿、type: referenceかな

**Comment by marihachi** [comment]
linkにしようと思ってたけどreferenceもアリ
