### ISSUE TITLE
PHPCS / Travis CIの導入

### ISSUE THREAD

**Issue by potato4d** [Frost-Dev/Frost-API#32]
とりあえずテスト関連は後にしても、TravisとPHPCSの設定ぐらいは先にやったほうが良さそう？

**Comment by marihachi** [comment]
なるほどー(やったことない)

**Comment by potato4d** [comment]
テスト関連は設計にもよるから構文周りだけだったらみりあやるよ

**Comment by potato4d** [comment]
取り敢えずPHPUnitサッと入れるには決めごと多すぎるので議題から外していきます

**Comment by marihachi** [comment]
Noneになったから、JavaScript用のテストフレームワークとか検討していきたい

**Comment by otofune** [comment]
mocha導入したからもう不要なIssueでは

**Comment by marihachi** [comment]
わかる

**Comment by marihachi** [comment]
あ、でもTravis CIはまだ

**Comment by otofune** [comment]
Travis Ciなんてザクザクやったらすぐ終わるんだからやっていこうぜ (Ownerじゃないと設定できないから俺には出来ないけど)

**Comment by marihachi** [comment]
p4dにadmin渡してするような雰囲気出してたけどもうやってあるんだろうか

**Comment by otofune** [comment]
設定にも依るけどそうだったらコミットの横が × になってるはず
P.S. .travis.yml がなければ走らせないっていう設定がある

**Comment by marihachi** [comment]
これだ
https://github.com/Frost-Dev/Frost-API/tree/feature-%2332

**Comment by otofune** [comment]
なるほどあるじゃねーか
ただPHPとはもう関連がないから使えなさそうだけど

**Comment by marihachi** [comment]
.travis.yml追加してみたけど、dbを使うテストとかはどうしようかといった感じ

**Comment by marihachi** [comment]
mongodb提供されてるやん神
