### ISSUE TITLE
コミュニティ機能の検討

### ISSUE THREAD

**Issue by marihachi** [Frost-Dev/Frost-API#38]
グループチャットとかできるようにしたいなって

**Comment by marihachi** [comment]
→ https://github.com/Frost-Dev/Frost/issues/1

**Comment by Asteriskx** [comment]
全て Node で完結できるように、ライブラリ？として組み込みたい。

**Comment by marihachi** [comment]
@Asteriskx モジュールとしてってこと？

**Comment by Asteriskx** [comment]
そんな感じかなー。
