### ISSUE TITLE
各種タイムラインのエンドポイントについて

### ISSUE THREAD

**Issue by marihachi** [Frost-Dev/Frost-API#61]
全エンドポイント一覧: https://github.com/Frost-Dev/Frost-API/blob/develop/src/routeList.js

## 配慮すること
ポストの種類は複数あるので、その一種類を対象としたタイムラインを取得できるほうがいい #62

## 案
- パブリックTL (フォローしているかに関係なく、一般公開されたポストを受け取れる)
  - `/general/timeline`
  - `/public/timeline`
  - `/instance/timeline`
  - `/timelines/public`

- ユーザーTL (対象ユーザーだけのTL。プロフ用)
  - `/users/:userId/timelines/user`

- ホームTL
  - `/users/:userId/timelines/home`
  - `/account/timelines/home`
  - `/timelines/home`
    - ※ユーザーごとに対象リソースが変わるのはイケてない感

- リストTL (のちのち必要そう？)
  - `/users/:userId/lists/:listId/timeline`
  - `/account/lists/:listId/timeline`
  - `/lists/:listId/timeline`
    - ※ユーザーごとに対象リソースが変わるのはイケてない感

## 組み合わせ案 A
ユーザー、ホーム、リスト、に関しては`/users/:id`下に置くの案が良さげ？
じゃあパブリックはどこへ...？
### 構成
- `/general/timeline`
- `/users/:userId/timelines/user`
- `/users/:userId/timelines/home`
- `/users/:userId/lists/:listId/timeline`

**Comment by Asteriskx** [comment]
public な TL って全体が フォロー関係になってなくても
観れる認識でok?

**Comment by marihachi** [comment]
そう

**Comment by marihachi** [comment]
以下の構成でやっていくことにします
- `/general/timeline`
- `/users/:userId/timelines/user`
- `/users/:userId/timelines/home`
- `/users/:userId/lists/:listId/timeline`

**Comment by marihachi** [comment]
issue立てました。これは閉じます
#63 #64 #65
